# Generated by Django 4.1.7 on 2023-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoornimaEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutaion', models.CharField(max_length=5)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('corresponding_email', models.EmailField(max_length=250)),
                ('contact', models.CharField(default=None, max_length=15, null=True)),
                ('university_college_name', models.CharField(max_length=50)),
                ('university_college_address', models.CharField(max_length=50)),
                ('university_college_city', models.CharField(max_length=50)),
            ],
        ),
    ]
